spring.application.name=projetoindividual
spring.datasource.url=jdbc:mysql://localhost:3306/reviewbox
spring.datasource.username=root
spring.datasource.password=Gabi@007

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true